name: ada36
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - scipy
  - statsmodels
  - pandas
  - matplotlib
  - seaborn
  - notebook
  - jupyterlab
  - jupyter
  - anaconda-navigator
  - flask
  - scikit-learn>=0.22
  - gitpython
